version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: library_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
