version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: library_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: library_backend
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - library-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: library_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - library-network

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
