version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: bibliotheque_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bibliotheque-network

volumes:
  postgres_data:

networks:
  bibliotheque-network:
    driver: bridge
